version: '3.8'

services:
  app:
    build: .
    container_name: fx-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - API_KEY=40e430afb8f65c528718af82b03d3b78
    networks:
      - fx-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fx-network

networks:
  fx-network:
    driver: bridge