version: '3.8'

services:
  app:
    build: .
    container_name: fx-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - API_KEY=${API_KEY}
    networks:
      - fx-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fx-network

networks:
  fx-network:
    driver: bridge